# Site settings
title: LuisMelo Multimédia
email: geral@luisfbmelo.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luisfbmelo.com" # the base hostname & protocol for your site
twitter_username: luisfbmelo
github_username:  luisfbmelo

# Build settings
markdown: kramdown

highlighter: rouge

#Exclude files and folders from compiling
exclude: [node_modules, package.json, js/app.js, js/plugins, js/custom_modules, Gruntfile.js]

#Excerpt
excerpt_separator: <!--more-->

#Num of posts
paginate: 3
paginate_path: "/blog/page/:num"

#Menu
pages_list:       
  Home: '/'
  Portfolio: '/portfolio/'
  Blog: '/blog/'

collections:
- portfolio

permalink: /blog/:year/:month/:day/:title/