# Site settings
title: Luis Melo
email: geral@luisfbmelo.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Portuguese UX/UI designer, front-end developer and also experienced with backend development, aiming to create usefull, clean and user-centered web and mobile experiences.	
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://luisfbmelo.github.io/" # the base hostname & protocol for your site
#url: "http://localhost:4000"
twitter_username: luisfbmelo
github_username:  luisfbmelo

# Build settings
markdown: kramdown

highlighter: rouge

# Show posts in future
future: true

#Exclude files and folders from compiling
exclude: [node_modules, package.json, js/app.js, js/plugins, js/custom_modules, Gruntfile.js]

#Excerpt
excerpt_separator: <!--more-->

#Num of posts
paginate: 6
paginate_path: "/blog/page/:num"

#Menu
pages_list:       
  Home: '/'
  Portfolio: '/portfolio/'
  Blog: '/blog/'

collections:
- portfolio

permalink: /blog/:year/:month/:day/:title/

#SASS
sass:
  style: compressed

#emoji
emoji_dir: /images/emoji

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-frontmatter-jsonify